# Generated by Django 6.0.5 on 2026-05-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='chemical',
            field=models.JSONField(default=dict, help_text='Composición química (C, Mn, Si, etc.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cortes',
            field=models.JSONField(default=list, help_text='Formatos disponibles (Redondo, Cuadrado...)'),
        ),
        migrations.AddField(
            model_name='product',
            name='equivalencias',
            field=models.JSONField(default=dict, help_text='Normativas internacionales'),
        ),
        migrations.AddField(
            model_name='product',
            name='gama_medidas',
            field=models.JSONField(default=dict, help_text='Rango de dimensiones por tipo'),
        ),
        migrations.AddField(
            model_name='product',
            name='mechanical',
            field=models.JSONField(default=dict, help_text='Propiedades mecánicas por diámetro'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=list, help_text='Lista de especificaciones técnicas'),
        ),
        migrations.AddField(
            model_name='product',
            name='suministros',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='table_config',
            field=models.CharField(default='plantilla_aceros', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Material sin nombre', max_length=255, verbose_name='Nombre del material'),
            preserve_default=False,
        ),
    ]
