# Generated by Django 6.0.5 on 2026-06-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_material_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='table_config',
        ),
    ]
